# Generated by Django 2.2.5 on 2021-07-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('born_date', models.DateField()),
            ],
            options={
                'db_table': 'tb_authors',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField()),
                ('country', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('hauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Author')),
            ],
            options={
                'db_table': 'tb_books',
            },
        ),
    ]
